version: "{branch}-{build}"

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files\Java\jdk9
    - JAVA_HOME: C:\Program Files\Java\jdk10

build:
  verbosity: detailed

build_script:
  - gradlew.bat --info --no-daemon test

cache:
  - C:\Users\appveyor\.gradle
